// This is a temporary file to help with development
// In a real setup, this would be generated by Convex

export type Doc<T extends string> = {
	_id: Id<T>;
	_creationTime: number;
} & any;

export type Id<T extends string> = string & { __tableName: T };
