// This is a temporary file to help with development
// In a real setup, this would be generated by Convex

export function query(config: any) {
	return config;
}

export function mutation(config: any) {
	return config;
}

export const v = {
	string: () => 'string',
	number: () => 'number',
	boolean: () => 'boolean',
	array: (item: any) => `array<${item}>`,
	object: (obj: any) => `object`,
	optional: (type: any) => `optional<${type}>`,
	union: (...types: any[]) => `union<${types.join('|')}>`,
	literal: (value: any) => `literal<${value}>`,
	id: (table: string) => `id<${table}>`
};
