fragment ArticleItem on Article {
  slug
  title
  summary
  category
  publishedAt
  defaultImage {
    data {
      id
      attributes {
        name
        url
        blurhash
        width
        height
      }
    }
  }
  author {
    data {
      id
      attributes {
        slug
        name
        avatar {
          data {
            id
            attributes {
              name
              url
              blurhash
              width
              height
            }
          }
        }
      }
    }
  }
}
