query HomePage {
  home {
    data {
      attributes {
        images(pagination: { limit: 10000 }) {
          data {
            attributes {
              name
              url
              width
              height
              hash
              mime
              provider
              size
            }
          }
        }
      }
    }
  }
  upcomingEvents: events(sort: "start:desc", pagination: { limit: 6 }) {
    data {
      id
      attributes {
        slug
        name
        start
        end
        timezone
        status
        description
        defaultImage {
          data {
            id
            attributes {
              name
              url
              blurhash
              width
              height
            }
          }
        }
        location {
          data {
            attributes {
              name
              country
            }
          }
        }
      }
    }
  }
  latestArticles: articles(sort: "publishedAt:desc", pagination: { limit: 3 }) {
    data {
      id
      attributes {
        slug
        title
        summary
        category
        publishedAt
        defaultImage {
          data {
            id
            attributes {
              name
              url
              blurhash
              width
              height
            }
          }
        }
        author {
          data {
            id
            attributes {
              slug
              name
              avatar {
                data {
                  id
                  attributes {
                    name
                    url
                    blurhash
                    width
                    height
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
