module.exports = ({ env }) => [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": [
            "'self'",
            "https:",
            "blob:",
            "*.strapi.io",
            "https://proxy-event.ckeditor.com",
            "https://cdn.ckeditor.com",
          ],
          "script-src": [
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "cdn.jsdelivr.net",
            "api.mapbox.com",
            "https://cdn.ckeditor.com",
          ],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "cdn.jsdelivr.net",
            "dl.airtable.com",
            "*.strapi.io",
            "s3.amazonaws.com",
            "https://cdn.ckeditor.com",
            process.env.STORAGE_URL,
            process.env.STORAGE_CDN_URL,
          ],
          "style-src": [
            "'self'",
            "'unsafe-inline'",
            "https://cdn.ckeditor.com",
          ],
          "font-src": [
            "'self'",
            "https://cdn.ckeditor.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "dl.airtable.com",
            process.env.STORAGE_URL,
            process.env.STORAGE_CDN_URL,
          ],
          "worker-src": ["'self'", "blob:"],
          "frame-src": ["'self'", "https://ckeditor.com", "https://*.ckeditor.com"],
          "object-src": ["'none'"],
          "base-uri": ["'self'"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
