/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import countrySelect from "strapi-plugin-country-select/strapi-admin";
import mapField from "strapi-plugin-map-field/strapi-admin";
import timezoneSelect from "strapi-plugin-timezone-select/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor5: ckeditor5,
    graphql: graphql,
    "users-permissions": usersPermissions,
    "config-sync": configSync,
    "country-select": countrySelect,
    "map-field": mapField,
    "timezone-select": timezoneSelect,
  },
});
